// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UHotel9;

#nullable disable

namespace UHotel9.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20231221075736_imgMig2")]
    partial class imgMig2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("UHotel9.Tables.Employee", b =>
                {
                    b.Property<string>("employeeId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("city")
                        .IsRequired()
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("country")
                        .IsRequired()
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("department")
                        .IsRequired()
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("employeeAge")
                        .HasColumnType("int");

                    b.Property<string>("employeeFname")
                        .IsRequired()
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("employeeLname")
                        .IsRequired()
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("employeePhone")
                        .IsRequired()
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("employeePhoto")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("employeeSalary")
                        .HasColumnType("decimal");

                    b.Property<int>("gender")
                        .HasColumnType("int");

                    b.Property<string>("status")
                        .IsRequired()
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("username")
                        .IsRequired()
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("employeeId");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("UHotel9.Tables.Guest", b =>
                {
                    b.Property<string>("guestId")
                        .HasMaxLength(14)
                        .HasColumnType("nvarchar(14)");

                    b.Property<string>("city")
                        .IsRequired()
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("country")
                        .IsRequired()
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("gender")
                        .HasColumnType("int");

                    b.Property<string>("guestFname")
                        .IsRequired()
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("guestLname")
                        .IsRequired()
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("roomId")
                        .HasColumnType("int");

                    b.Property<string>("status")
                        .IsRequired()
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("guestId");

                    b.HasIndex("roomId");

                    b.ToTable("Guests");
                });

            modelBuilder.Entity("UHotel9.Tables.Reservation", b =>
                {
                    b.Property<int>("reservationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("reservationId"));

                    b.Property<DateTime>("checkInDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("checkOutDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("guestId")
                        .IsRequired()
                        .HasColumnType("nvarchar(14)");

                    b.Property<int?>("roomId")
                        .HasColumnType("int");

                    b.HasKey("reservationId");

                    b.HasIndex("guestId");

                    b.HasIndex("roomId");

                    b.ToTable("Reservations");
                });

            modelBuilder.Entity("UHotel9.Tables.Room", b =>
                {
                    b.Property<int>("roomId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("roomId"));

                    b.Property<int>("floorNumber")
                        .HasColumnType("int");

                    b.Property<decimal>("price")
                        .HasColumnType("decimal");

                    b.Property<int>("type")
                        .HasColumnType("int");

                    b.HasKey("roomId");

                    b.ToTable("Rooms");
                });

            modelBuilder.Entity("UHotel9.Tables.Guest", b =>
                {
                    b.HasOne("UHotel9.Tables.Room", "Room")
                        .WithMany("Guests")
                        .HasForeignKey("roomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Room");
                });

            modelBuilder.Entity("UHotel9.Tables.Reservation", b =>
                {
                    b.HasOne("UHotel9.Tables.Guest", "Guest")
                        .WithMany("Reservations")
                        .HasForeignKey("guestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UHotel9.Tables.Room", "Room")
                        .WithMany("Reservations")
                        .HasForeignKey("roomId");

                    b.Navigation("Guest");

                    b.Navigation("Room");
                });

            modelBuilder.Entity("UHotel9.Tables.Guest", b =>
                {
                    b.Navigation("Reservations");
                });

            modelBuilder.Entity("UHotel9.Tables.Room", b =>
                {
                    b.Navigation("Guests");

                    b.Navigation("Reservations");
                });
#pragma warning restore 612, 618
        }
    }
}
